### ISSUE TITLE
Making a payment with this plugin

### ISSUE THREAD

**Issue by AwesomeJ0sh** [zyra/cordova-plugin-stripe#33]
Hello,
I am building and Ionic 3 app. For web, android and iOS.

I would like users to be able to make payments with this plugins.

Is it possible?
Using the basic usage code I have been able to add a test credit card to POST /v1/tokens.
But I want to charge it. 

docs say 
"Once you have the token, you can now send it to your backend so you can charge the customer later on."

What function "sends it to my backend"?

how is this done? like this?
[stripe docs Charge immediately](https://stripe.com/docs/quickstart#charge-immediately)

if so which language?(Ionic 3 is in typescript). I see no .charges function in the plugin to charge with. Am I missing something?

here is my code. any insight is appreciated. 

`
//stripe declared in constructor earlier.

testPay(){
    this.stripe.setPublishableKey('pk_test_7Rywuc5EH1tavYiXXX');

        let card = {
        number: '4242424242424242',
        expMonth: 12,
        expYear: 2020,
        cvc: '220'
        };

    this.stripe.createCardToken(card)
     .then(token => alert('token: ' +JSON.stringify(token)))
     .catch(error => alert('error: ' +error));
  }`

**Comment by ihadeed** [comment]
You should have a backend that processes payments. Your frontend (app) should collect credit card information, then use the plugin to send this information to Stripe. The plugin will then provide you with a token. This token can be sent to your backend, and then used to charge the customer or subscribing them to some membership. 

This plugin only wraps the mobile SDKs provided by Stripe. It's not going to have an HTTP client that speaks to Stripe on your behalf. Charging users require including your secret key in the app, which is an unsafe practice. If you want to charge users through the app without a backend, you can send an HTTP request using your secret key (**do this at your own risk**).

**Comment by AwesomeJ0sh** [comment]
Thanks for your information.

What would be the best/safest way to process a payment after I have used this plugin to get/send a token? Through the stripe dashboard? 

what are the dangers of including the secret key in the app and processing the payment without a back end?

**Comment by ihadeed** [comment]
I usually have a Node.JS based backend (Express.JS) that handles data, authentication, and payments. I use Stripe's Node.js library to process the stripe payments. The usual process goes like this:
- Collect credit card payments in the front end, and send it to Stripe using their SDK (JavaScript, Android, iOS ...etc)
- If the credit card info is valid, I receive a token from Stripe. This token is the only thing I send to the back end. It is safe to send it because no one can use it unless if they have my secret key (that matches the publishable key I use in the front end). This way I will not risk my customer's credit card information, and I make sure that only Stripe gets to see that information. 
- Use server-side Stripe SDK to send them the token. I can either use the token to charge their credit card immediately, or save it in the customer's profile (on Stripe) to charge them at a later date or subscribe them to some sort of monthly/annual membership.

Anything that you include in your app's source code can be acquired by reverse engineering. If someone acquires your secret key, they will be able to use all the Stripe API features. Which means they will get to pull customer data, payment history, issue refunds, charge customers with money they're not supposed to be charged... etc.

**Comment by AwesomeJ0sh** [comment]
I understand. I am using firebase as my back end (database and auth). Would any of these integrations be secure enough?

A: Keep the secret key on the database and only pass it to the app when necessary to make a payment?

B: Storing the tokens on a database to then make payments with a local server once a day.

C: Using the [Firebase Functions](https://firebase.google.com/docs/functions/use-cases) Specifically, Integrate with third-party services and APIs.

I am leaning towards C. But any thoughts you might have are appreciated.

**Comment by ihadeed** [comment]
Sending the key to the app is also unsafe.

Processing payments once a day isn't a good user experience. But that
depends on your customers. Also, I think tokens expire...

I suggest using Amazon Lambda. Also check "Serverless". You can make server
code that runs only when you wanna charge a customer. This will cost you
only a few cents. You can add that cost to the payment fees too.

May I ask what are you charging customers for? If you're selling them an
app feature or anything app related, you must use in app purchase plugin.

Regards,
Ibby Hadeed

**Comment by AwesomeJ0sh** [comment]
Thank you, I will look into Amazon Lambda. seems to be a fairly simple way to do it and will integrate with firebase. 
Are there any disadvantages to using firebase functions over Amazon Lambda? besides price?

I am getting users to pay registration fees for events they plan to attend in the future. Sort of like buying tickets.

**Comment by ihadeed** [comment]
Not so sure. I don't use firebase.

Regards,
Ibby Hadeed

**Comment by AwesomeJ0sh** [comment]
Thanks for your info. Great plugin!
